uses:
  - django
  - celery


pylint:
  disable:
    - django-not-configured
    - import-outside-toplevel
    - unused-import

pyflakes:
  disable:
    - F401

pycodestyle:
  max-line-length: 300


ignor-path:
  - .venv

ignore-patterns:
  - .*migrations